export const LOAD_ADMIN_USERS_START = "LOAD_ADMIN_USERS_START";
export const LOAD_ADMIN_USERS_SUCCESS = "LOAD_ADMIN_USERS_SUCCESS";
export const LOAD_ADMIN_USERS_ERROR = "LOAD_ADMIN_USERS_ERROR";

export const CREATE_ADMIN_USER_START = "CREATE_ADMIN_USER_START";
export const CREATE_ADMIN_USER_SUCCESS = "CREATE_ADMIN_USER_SUCCESS";
export const CREATE_ADMIN_USER_ERROR = "CREATE_ADMIN_USER_ERROR";

export const DELETE_ADMIN_USER_START = "DELETE_ADMIN_USER_START";
export const DELETE_ADMIN_USER_SUCCESS = "DELETE_ADMIN_USER_SUCCESS";
export const DELETE_ADMIN_USER_ERROR = "DELETE_ADMIN_USER_ERROR";

export const UPDATE_ADMIN_USER_START = "UPDATE_ADMIN_USER_START";
export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS";
export const UPDATE_ADMIN_USER_ERROR = "UPDATE_ADMIN_USER_ERROR";

//New

export const SEARCH_ADMIN_USER_START = "SEARCH_ADMIN_USER_START";
export const SEARCH_ADMIN_USER_SUCCESS = "SEARCH_ADMIN_USER_SUCCESS";
export const SEARCH_ADMIN_USER_ERROR = "SEARCH_ADMIN_USER_ERROR";

export const FILTER_ADMIN_USER_START = "FILTER_ADMIN_USER_START";
export const FILTER_ADMIN_USER_SUCCESS = "FILTER_ADMIN_USER_SUCCESS";
export const FILTER_ADMIN_USER_ERROR = "FILTER_ADMIN_USER_ERROR";

export const SORT_ADMIN_USER_START = "SORT_ADMIN_USER_START";
export const SORT_ADMIN_USER_SUCCESS = "SORT_ADMIN_USER_SUCCESS";
export const SORT_ADMIN_USER_ERROR = "SORT_ADMIN_USER_ERROR";


/*-------------------Administrator--------------------*/

