export const LOAD_CLEANER_USERS_START = "LOAD_CLEANER_USERS_START";
export const LOAD_CLEANER_USERS_SUCCESS = "LOAD_CLEANER_USERS_SUCCESS";
export const LOAD_CLEANER_USERS_ERROR = "LOAD_CLEANER_USERS_ERROR";

export const CREATE_CLEANER_USER_START = "CREATE_CLEANER_USER_START";
export const CREATE_CLEANER_USER_SUCCESS = "CREATE_CLEANER_USER_SUCCESS";
export const CREATE_CLEANER_USER_ERROR = "CREATE_CLEANER_USER_ERROR";

export const DELETE_CLEANER_USER_START = "DELETE_CLEANER_USER_START";
export const DELETE_CLEANER_USER_SUCCESS = "DELETE_CLEANER_USER_SUCCESS";
export const DELETE_CLEANER_USER_ERROR = "DELETE_CLEANER_USER_ERROR";

export const UPDATE_CLEANER_USER_START = "UPDATE_CLEANER_USER_START";
export const UPDATE_CLEANER_USER_SUCCESS = "UPDATE_CLEANER_USER_SUCCESS";
export const UPDATE_CLEANER_USER_ERROR = "UPDATE_CLEANER_USER_ERROR";
//New

export const SEARCH_CLEANER_USER_START = "SEARCH_CLEANER_USER_START";
export const SEARCH_CLEANER_USER_SUCCESS = "SEARCH_CLEANER_USER_SUCCESS";
export const SEARCH_CLEANER_USER_ERROR = "SEARCH_CLEANER_USER_ERROR";

export const FILTER_CLEANER_USER_START = "FILTER_CLEANER_USER_START";
export const FILTER_CLEANER_USER_SUCCESS = "FILTER_CLEANER_USER_SUCCESS";
export const FILTER_CLEANER_USER_ERROR = "FILTER_CLEANER_USER_ERROR";

export const SORT_CLEANER_USER_START = "SORT_CLEANER_USER_START";
export const SORT_CLEANER_USER_SUCCESS = "SORT_CLEANER_USER_SUCCESS";
export const SORT_CLEANER_USER_ERROR = "SORT_CLEANER_USER_ERROR";