export const LOAD_CLIENT_USERS_START = "LOAD_CLIENT_USERS_START";
export const LOAD_CLIENT_USERS_SUCCESS = "LOAD_CLIENT_USERS_SUCCESS";
export const LOAD_CLIENT_USERS_ERROR = "LOAD_CLIENT_USERS_ERROR";

export const CREATE_CLIENT_USER_START = "CREATE_CLIENT_USER_START";
export const CREATE_CLIENT_USER_SUCCESS = "CREATE_CLIENT_USER_SUCCESS";
export const CREATE_CLIENT_USER_ERROR = "CREATE_CLIENT_USER_ERROR";

export const DELETE_CLIENT_USER_START = "DELETE_CLIENT_USER_START";
export const DELETE_CLIENT_USER_SUCCESS = "DELETE_CLIENT_USER_SUCCESS";
export const DELETE_CLIENT_USER_ERROR = "DELETE_CLIENT_USER_ERROR";

export const UPDATE_CLIENT_USER_START = "UPDATE_CLIENT_USER_START";
export const UPDATE_CLIENT_USER_SUCCESS = "UPDATE_CLIENT_USER_SUCCESS";
export const UPDATE_CLIENT_USER_ERROR = "UPDATE_CLIENT_USER_ERROR";

//New

export const SEARCH_CLIENT_USER_START = "SEARCH_CLIENT_USER_START";
export const SEARCH_CLIENT_USER_SUCCESS = "SEARCH_CLIENT_USER_SUCCESS";
export const SEARCH_CLIENT_USER_ERROR = "SEARCH_CLIENT_USER_ERROR";

export const FILTER_CLIENT_USER_START = "FILTER_CLIENT_USER_START";
export const FILTER_CLIENT_USER_SUCCESS = "FILTER_CLIENT_USER_SUCCESS";
export const FILTER_CLIENT_USER_ERROR = "FILTER_CLIENT_USER_ERROR";

export const SORT_CLIENT_USER_START = "SORT_CLIENT_USER_START";
export const SORT_CLIENT_USER_SUCCESS = "SORT_CLIENT_USER_SUCCESS";
export const SORT_CLIENT_USER_ERROR = "SORT_CLIENT_USER_ERROR";