export const LOAD_DRIVER_USERS_START = "LOAD_DRIVER_USERS_START";
export const LOAD_DRIVER_USERS_SUCCESS = "LOAD_DRIVER_USERS_SUCCESS";
export const LOAD_DRIVER_USERS_ERROR = "LOAD_DRIVER_USERS_ERROR";

export const CREATE_DRIVER_USER_START = "CREATE_DRIVER_USER_START";
export const CREATE_DRIVER_USER_SUCCESS = "CREATE_DRIVER_USER_SUCCESS";
export const CREATE_DRIVER_USER_ERROR = "CREATE_DRIVER_USER_ERROR";

export const DELETE_DRIVER_USER_START = "DELETE_DRIVER_USER_START";
export const DELETE_DRIVER_USER_SUCCESS = "DELETE_DRIVER_USER_SUCCESS";
export const DELETE_DRIVER_USER_ERROR = "DELETE_DRIVER_USER_ERROR";

export const UPDATE_DRIVER_USER_START = "UPDATE_DRIVER_USER_START";
export const UPDATE_DRIVER_USER_SUCCESS = "UPDATE_DRIVER_USER_SUCCESS";
export const UPDATE_DRIVER_USER_ERROR = "UPDATE_DRIVER_USER_ERROR";

export const SEARCH_DRIVER_USER_START = "SEARCH_DRIVER_USER_START";
export const SEARCH_DRIVER_USER_SUCCESS = "SEARCH_DRIVER_USER_SUCCESS";
export const SEARCH_DRIVER_USER_ERROR = "SEARCH_DRIVER_USER_ERROR";

export const FILTER_DRIVER_USER_START = "FILTER_DRIVER_USER_START";
export const FILTER_DRIVER_USER_SUCCESS = "FILTER_DRIVER_USER_SUCCESS";
export const FILTER_DRIVER_USER_ERROR = "FILTER_DRIVER_USER_ERROR";

export const SORT_DRIVER_USER_START = "SORT_DRIVER_USER_START";
export const SORT_DRIVER_USER_SUCCESS = "SORT_DRIVER_USER_SUCCESS";
export const SORT_DRIVER_USER_ERROR = "SORT_DRIVER_USER_ERROR";