export const LOAD_DROPOFFS_START = "LOAD_DROPOFFS_START";
export const LOAD_DROPOFFS_SUCCESS = "LOAD_DROPOFFS_SUCCESS";
export const LOAD_DROPOFFS_ERROR = "LOAD_DROPOFFS_ERROR";

export const CREATE_DROPOFF_START = "CREATE_DROPOFF_START";
export const CREATE_DROPOFF_SUCCESS = "CREATE_DROPOFF_SUCCESS";
export const CREATE_DROPOFF_ERROR = "CREATE_DROPOFF_ERROR";

export const DELETE_DROPOFF_START = "DELETE_DROPOFF_START";
export const DELETE_DROPOFF_SUCCESS = "DELETE_DROPOFF_SUCCESS";
export const DELETE_DROPOFF_ERROR = "DELETE_DROPOFF_ERROR";

export const UPDATE_DROPOFF_START = "UPDATE_DROPOFF_START";
export const UPDATE_DROPOFF_SUCCESS = "UPDATE_DROPOFF_SUCCESS";
export const UPDATE_DROPOFF_ERROR = "UPDATE_DROPOFF_ERROR";

export const SEARCH_DROPOFF_START = "SEARCH_DROPOFF_START";
export const SEARCH_DROPOFF_SUCCESS = "SEARCH_DROPOFF_SUCCESS";
export const SEARCH_DROPOFF_ERROR = "SEARCH_DROPOFF_ERROR";

export const FILTER_DROPOFF_START = "FILTER_DROPOFF_START";
export const FILTER_DROPOFF_SUCCESS = "FILTER_DROPOFF_SUCCESS";
export const FILTER_DROPOFF_ERROR = "FILTER_DROPOFF_ERROR";

export const SORT_DROPOFF_START = "SORT_DROPOFF_START";
export const SORT_DROPOFF_SUCCESS = "SORT_DROPOFF_SUCCESS";
export const SORT_DROPOFF_ERROR = "SORT_DROPOFF_ERROR";