export const LOAD_PICKUPS_START = "LOAD_PICKUPS_START";
export const LOAD_PICKUPS_SUCCESS = "LOAD_PICKUPS_SUCCESS";
export const LOAD_PICKUPS_ERROR = "LOAD_PICKUPS_ERROR";

export const CREATE_PICKUP_START = "CREATE_PICKUP_START";
export const CREATE_PICKUP_SUCCESS = "CREATE_PICKUP_SUCCESS";
export const CREATE_PICKUP_ERROR = "CREATE_PICKUP_ERROR";

export const DELETE_PICKUP_START = "DELETE_PICKUP_START";
export const DELETE_PICKUP_SUCCESS = "DELETE_PICKUP_SUCCESS";
export const DELETE_PICKUP_ERROR = "DELETE_PICKUP_ERROR";

export const UPDATE_PICKUP_START = "UPDATE_PICKUP_START";
export const UPDATE_PICKUP_SUCCESS = "UPDATE_PICKUP_SUCCESS";
export const UPDATE_PICKUP_ERROR = "UPDATE_PICKUP_ERROR";

export const SEARCH_PICKUP_START = "SEARCH_PICKUP_START";
export const SEARCH_PICKUP_SUCCESS = "SEARCH_PICKUP_SUCCESS";
export const SEARCH_PICKUP_ERROR = "SEARCH_PICKUP_ERROR";

export const FILTER_PICKUP_START = "FILTER_PICKUP_START";
export const FILTER_PICKUP_SUCCESS = "FILTER_PICKUP_SUCCESS";
export const FILTER_PICKUP_ERROR = "FILTER_PICKUP_ERROR";

export const SORT_PICKUP_START = "SORT_PICKUP_START";
export const SORT_PICKUP_SUCCESS = "SORT_PICKUP_SUCCESS";
export const SORT_PICKUP_ERROR = "SORT_PICKUP_ERROR";